added OAuth
erdl/survey_admin pull request #34
Opened 2018-01-20 01:28 UTC by jygh98

This PR is regarding #23, we are now able to authenticate users through Google's OAuth API and permit whitelisted users whose added to the database.

2018-02-08 00:54 UTC, carlosparadis requested changes
@jygh98 I've listed inline the requested changes below. **Do not erase the current commit on your fork, or edit it. For now, just create a new commit addressing the issues. This will make it much easier for me to see what you did to fix the pointed problems.**

Only after we agree on the following changes, then we can discuss merging both of them into one. 

Let me know if this doesn't make sense. Worst case scenario you may end up deleting all the review notes I made permanently if you are not on the same page.

2018-02-08 00:54 UTC, carlosparadis commented on ubuntuStation/views.py
> +    SECRET_KEY = "development"
@ryantanaka @jygh98 is this safe to be here? If not, need to get a new secret key and follow the same procedure we did for the other information.

2018-02-08 00:54 UTC, carlosparadis commented on ubuntuStation/views.py
> +@app.route('/showusers', methods=['GET'])
This should be mentioned in the original issue. I was expecting only the login page to have been changed. Others may not be aware for the same reason.

2018-02-08 00:54 UTC, carlosparadis commented on ubuntuStation/templates/base.html
> +							<li><a href="{{ url_for('show_users') }}">Manage Users</a></li>
The "manage users" option added to the menu should be mentioned in the original issue. I was expecting only the login page to have been changed. Others may not be aware for the same reason.

2018-02-08 00:54 UTC, carlosparadis commented on ubuntuStation/templates/user_form.html
> +<h1>Add User</h1>
Adding new users page should be mentioned in the original issue. I was expecting only the login page to have been changed. Others may not be aware for the same reason.

The name of the file also does not portray its purpose. `create_user.html` as the form action name suggests would be better and avoid conflicts in the long run with other file names should we decide to create other forms associated to users.

2018-02-08 00:54 UTC, carlosparadis commented on ubuntuStation/views.py
> +@app.route('/logout')
Nice catch.

2018-02-08 00:54 UTC, carlosparadis commented on ubuntuStation/models.py
> +class User(db.Model, UserMixin):
What tables and columns were modified? Just User?

2018-02-08 00:54 UTC, carlosparadis commented on ubuntuStation/templates/login.html
> +<a href="{{auth_url}}" class="btn";"><img src="static/google_login.png" width="335.2" height="68.8"></a>
This file change and associated files that enabled `auth_url` are actually the ones truly associated with the title of the PR and Issue (i.e. adds oAuth). Showing users or adding them, albeit related are not required. As such, they need to be explicitly mentioned on issue+pr+commit.

2018-02-08 00:54 UTC, carlosparadis commented on run.py
>  app.run(debug=True, host='0.0.0.0', port=8989)
Is this port here safe (i.e. it is not matching with the apache one, right?)? Also, what is this `insecure transport` equals true about? Looks fishy!

2018-02-16 02:38 UTC, ryantanaka commented
@ryantanaka

### feature branches
- add oauth
- views.py: remove lines 21-23 (not needed in our case, only for other oauth related features)
- views.py: line 104, uncovered this small mixup here just gonna include it as a separate commit
- models.py: this is to replace the users table (we will need to update this on the database)
- login.html: part of this branch 
- run.py: part of this branch (yes this appears to secure, we've checked some stackoverflow references and will include the link in the PR for reference)

### add  users through survey_admin instead of manually changing the database 
-  views.py: line 323 - 326 can be part of this branch it is a separate feature
- base.html: this relates only to adding oauth users, not to adding oauth
- user_form.html: need to change this to something like create_oauth_user.html

2018-02-21 08:19 UTC, carlosparadis commented
The portion associated to Google Login via OAuth has been merged on PR #44

2018-02-21 08:19 UTC, closed without merging

2018-09-22 00:09 UTC, ryantanaka commented on ubuntuStation/views.py
> +            user.name = user_data['name']
@carlosparadis , we don't use user.name anywhere else. I will be removing this. For some reason, `name` was a valid key in the json response that we get, however it no longer is and so we get an error. Fixing it here in 
https://github.com/erdl/survey_admin/issues/64

2018-09-22 00:22 UTC, carlosparadis commented
@ryantanaka send on a different PR/issue. Im slightly confused what is this about.

2018-09-22 00:27 UTC, ryantanaka commented
yeah i have an issue open already, but im still looking into why this happened.
i wanted to put this comment here so we know when it was added